### ISSUE TITLE
ChecksumMismatchError: SHA256 mismatch On Install

### ISSUE THREAD

**Issue by JonnyBoy333** [limebox/homebrew-netsuite#8]
Was trying to update to the latest SDFCLI today and ran into this problem:

```Error: An exception occurred within a child process:
ChecksumMismatchError: SHA256 mismatch
Expected: dec6dcb34202a3b1e56a47c274e34d6899632e89767516e7f2ec6ea1eae4d299
Actual: eda2e440a374cb226b15ba6cc5b5e9b9824acf2203f0882c6c81f3d0ac2e841c
```

I tried downloading SDF from the official "Installing SDF SDK" page in NetSuite the help center and checked the checksum and it is indeed `eda2e440a374cb226b15ba6cc5b5e9b9824acf2203f0882c6c81f3d0ac2e841c`. Can I update the expected checksum in this tool through a setting or something to avoid this error?

**Comment by tjtyrrell** [comment]
Thanks for bringing this to my attention. I'll have this fixed tonight.
They keep changing the file on me.

**Comment by JonnyBoy333** [comment]
No problem. I should let you know that I did create a fork to try to update this myself. I hit a different problem after fixing the checksum

```
Error: An exception occurred within a child process:
Errno::ENOENT: No such file or directory - cli-2019.2.0.jar
```
I'm guessing `cli-2019.2.0.jar` isn't the correct filename, though I'm a little unsure on this one since I don't know what's getting downloaded from limebox in the curl command.

**Comment by tjtyrrell** [comment]
It's possible that this is related to the 19.2 update. Depending on the
variables you updated in the recipe, NetSuite does some funky things with
the cli downloads. Once they finalize the npm package I'll probably
discontinue this one. Between the finicky nature of the NetSuite team and
brew releasing several breaking changes this year, it's been more of a
headache to keep up on.

In either case, thank you again for being this to my attention. I'm on a
train right now but will be about to fix this in the next hour in time for
the work week.

**Comment by JonnyBoy333** [comment]
Ah, I forgot about the npm package. Well that would be a better way to go, but who knows when NetSuite will get around to releasing it. Thanks for the quick updates, a couple of us at my office use your tool regularly.

**Comment by tjtyrrell** [comment]
Thank you for your support @JonnyBoy333 

Please try the install again. Unfortunately I am not near my Mac and am unable to test my fix. But it should work.

**Comment by JonnyBoy333** [comment]
Yes, that did the trick.
